# Conda environment file for meshlearn.
name: meshlearn
channels:
  - defaults
  - conda-forge
dependencies:
  - lightgbm >= 3.2
  - igl >= 2.2
  - scikit-learn >= 1.0
  - trimesh >= 3.0
  - pandas >= 1.3
  - nibabel >= 2.1

